/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TicketId = IDL.Nat;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Ticket = IDL.Record({
  'id' : TicketId,
  'status' : TicketStatus,
  'creator' : IDL.Principal,
  'description' : IDL.Text,
  'targetRole' : UserRole,
});
export const UserRow = IDL.Record({
  'userId' : IDL.Principal,
  'profile' : UserProfile,
});
export const WithdrawStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawStatus,
  'creator' : IDL.Principal,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkRoleAndStatus' : IDL.Func(
      [],
      [IDL.Record({ 'role' : IDL.Text, 'isActive' : IDL.Bool })],
      ['query'],
    ),
  'claimSuperadmin' : IDL.Func([], [IDL.Bool], []),
  'createTicket' : IDL.Func([IDL.Text, UserRole], [TicketId], []),
  'createWithdrawRequest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalTasks' : IDL.Nat,
          'totalTicketsOpen' : IDL.Nat,
          'totalClients' : IDL.Nat,
          'totalPartners' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalWithdrawPending' : IDL.Nat,
          'totalLayanan' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSuperadminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasSuperadmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSuperadmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserRow)], ['query']),
  'listAllWithdrawRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawRequest)],
      ['query'],
    ),
  'listMyTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'listMyWithdrawRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawRequest)],
      ['query'],
    ),
  'listTicketsByTargetRole' : IDL.Func(
      [UserRole],
      [IDL.Vec(Ticket)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserActiveStatus' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
  'updateTicketStatus' : IDL.Func([TicketId, TicketStatus], [], []),
  'updateWithdrawStatus' : IDL.Func([IDL.Nat, WithdrawStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TicketId = IDL.Nat;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Ticket = IDL.Record({
    'id' : TicketId,
    'status' : TicketStatus,
    'creator' : IDL.Principal,
    'description' : IDL.Text,
    'targetRole' : UserRole,
  });
  const UserRow = IDL.Record({
    'userId' : IDL.Principal,
    'profile' : UserProfile,
  });
  const WithdrawStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawStatus,
    'creator' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkRoleAndStatus' : IDL.Func(
        [],
        [IDL.Record({ 'role' : IDL.Text, 'isActive' : IDL.Bool })],
        ['query'],
      ),
    'claimSuperadmin' : IDL.Func([], [IDL.Bool], []),
    'createTicket' : IDL.Func([IDL.Text, UserRole], [TicketId], []),
    'createWithdrawRequest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalTasks' : IDL.Nat,
            'totalTicketsOpen' : IDL.Nat,
            'totalClients' : IDL.Nat,
            'totalPartners' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalWithdrawPending' : IDL.Nat,
            'totalLayanan' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSuperadminPrincipal' : IDL.Func(
        [],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasSuperadmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSuperadmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserRow)], ['query']),
    'listAllWithdrawRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawRequest)],
        ['query'],
      ),
    'listMyTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'listMyWithdrawRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawRequest)],
        ['query'],
      ),
    'listTicketsByTargetRole' : IDL.Func(
        [UserRole],
        [IDL.Vec(Ticket)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserActiveStatus' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
    'updateTicketStatus' : IDL.Func([TicketId, TicketStatus], [], []),
    'updateWithdrawStatus' : IDL.Func([IDL.Nat, WithdrawStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };